name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.427'
        
    - name: Restore dependencies
      working-directory: src/TowerDefense.Tests
      run: dotnet restore
      
    - name: Build
      working-directory: src/TowerDefense.Tests
      run: dotnet build --no-restore
      
    - name: Unit tests with coverage
      working-directory: src/TowerDefense.Tests
      run: dotnet test --filter "FullyQualifiedName~Handlers" /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:Include="[TowerDefense.Api]TowerDefense.Api.GameLogic.Handlers.*"

    - name: Integration test
      working-directory: src/TowerDefense.Tests
      run: dotnet test --filter "FullyQualifiedName~IntegrationTest"

